FROM python:3.12

WORKDIR /code

# Install system dependencies required for potential Python packages
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# ENV PIP_DEFAULT_TIMEOUT=120

# Install Poetry
RUN pip install poetry

# Copy only the necessary files to avoid unnecessary cache invalidation
COPY pyproject.toml /code/

# Install Python dependencies
RUN poetry install

# Copy the rest of the application code
COPY . /code/


# EXPOSE  8000:9000

CMD ["poetry", "run", "uvicorn", "src.main:app", "--host", "0.0.0.0", "--reload"]
