FROM node:20-alpine

# Set the working directory in the container
WORKDIR /code

# Copy package.json and package-lock.json (if present)
# This allows us to install dependencies first and cache them in Docker layers
COPY package*.json /code/

# Install dependencies
RUN npm install --legacy-peer-deps

# Copy the rest of the application code
COPY . /code/

# EXPOSE  4001:3000

CMD ["npm", "run", "dev"]
