"""adding role_1 user default

Revision ID: 53aed43f5a70
Revises: 6cb6d67b2c89
Create Date: 2024-09-17 05:39:48.177799

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53aed43f5a70'
down_revision: Union[str, None] = '6cb6d67b2c89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
